### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by rachit1601** [Halocrypt/core#3]
Hey, I need help.(not related to the current cryptic hunt) . I wanna deploy this for my own. And if you r on discord, then it would be better. @Hydrophobefireman

**Comment by Hydrophobefireman** [comment]
what's your discord

**Comment by rachit1601** [comment]
> what's your discord
DiluteWater#3149

**Comment by rachit1601** [comment]
@Hydrophobefireman

**Comment by rachit1601** [comment]
@Hydrophobefireman ?

**Comment by Hydrophobefireman** [comment]
ok
